# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  test:
    runs-on: ubuntu-latest #${{ matrix.os }}
    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.21.5', '1.18.0']
        os: [ubuntu-latest, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Goec
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.5 #${{ matrix.go_version }}

    - name: Build Database Image
      run: docker-compose build

    - name: Create Database  
      run: docker-compose up -d
      
    - name: Test
      run: go test -v main_test.go

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -o bin/main.go
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        # Artifact name
        name: drop # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: bin/main.*

  docker:
   needs: build
   uses: ./.github/workflows/docker.yml
   secrets: inherit
            
